site_name: Kubernetes Study Env
site_url: https://bpgould.github.io/kubernetes-study-env/
nav:
  - Home: index.md
  - Getting Started: getting-started.md
theme:
  name: material
  palette:
    primary: teal
